FROM node:15.4 as build 

WORKDIR /my-app


COPY package*.json .


RUN yarn install


COPY . .


RUN yarn run build


FROM nginx:1.19


COPY ./nginx/nginx.conf /etc/nginx/nginx.conf


COPY --from=build /my-app/build /usr/share/nginx/html